spring.application.name=mcp-server
spring.main.bannerMode=off
#spring.ai.mcp.server.protocol=STATELESS
server.port=8085
userservice.url=${USER_SERVICE_URL}
spring.ai.mcp.server.name=app-mcp-server
spring.ai.mcp.server.version=1.0.0
logging.level.org.springframework.ai=DEBUG
#spring.ai.mcp.server.type=SYNC
