spring.application.name=ws
server.port=8084
spring.jpa.show-sql=true

spring.datasource.url=${USER_DB_URL}
spring.datasource.username=${USER_DB_USER}
spring.datasource.password=${USER_DB_PASS}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7
mcpserver.url=${MCP_SERVER_URL}
#spring.ai.mcp.client.streamable-http.connections.mcp-server.url=${MCP_SERVER_URL}
#spring.ai.mcp.client.type=SYNC
#spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.sse.connections.app-mcp-server.url=${MCP_SERVER_URL}
logging.level.org.springframework.ai=DEBUG



