application.name = UserService
server.port=8080
spring.jpa.show-sql=true
spring.cache.type=redis

spring.datasource.url=${USER_DB_URL}
spring.datasource.username=${USER_DB_USER}
spring.datasource.password=${USER_DB_PASS}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
app.ws.url=${APP_WS_URL:ws//localhost:8090/ws}
