application.name = AuthService
server.port=8082

spring.datasource.url=${USER_DB_URL}
spring.datasource.username=${USER_DB_USER}
spring.datasource.password=${USER_DB_PASS}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}


